name: cicd calc
on:
  push:
  workflow_dispatch:

jobs:
  # проверка python кода bandit'ом
  sast:
    name: Bandit Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install bandit
        run:
          pip install bandit safety
      - name: scan
        # если будут угрозы уровня "высокий", то bandit вернет код 1 и стадия sast остановится
        run: |
          bandit "Calculator.py"
          bandit "Calculator.py" > bandit_output.txt
      # загружаем файл bandit_output.txt в качестве артефакта 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: bandit_output.txt
          name: bandit_output.txt
      # получаем артефакт
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: bandit_output.txt

  build:
    runs-on: ubuntu-22.04
    needs: sast
    steps:
      # получаем репозиторий с гитхаба
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      # билдим образ и отправляем его в Docker Hub
      - name: Publishing a Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calc_flask:latest

  deploy:
    name: remote to host
    runs-on: ubuntu-22.04
    needs: build
    # подключаемся к серверу(vds) и выполняем команду по запуску контейнера
    steps:
      - name: remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script:
            "docker run -d -p 5000:5000 --name ${{ secrets.DOCKER_CONTAINER_NAME }} artemambrush/calc_flask"

  test:
    needs: deploy
    runs-on: ubuntu-22.04
    steps:
      # записываем то, что вывел curl при подключении к нашему калькулятору в файл output.txt
      - name: run curl and cat commands
        run: |
          curl -o output.txt "http://${{ secrets.HOST }}:5000/calc?arg1=10&arg2=7&operation=mult"
          cat output.txt
      # загружаем файл output.txt в качестве артефакта 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: output.txt
          name: out_curl
      # получаем артефакт
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: out_curl
  
  # останавливаем контейнер и удаляем его
  stop_containers:
    name: Stop and delete container
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: login in host and stoping docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script:
            "docker stop ${{ secrets.DOCKER_CONTAINER_NAME }}; docker system prune -a -f; exit"
