name: cicd calc
on:
  push:
  workflow_dispatch:
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # билдим образ и отправляем его в Docker Hub
      - name: Publishing a Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: artemambrush/calc_flask:latest

      #- name: build docker
      #  run: |
      #    echo "Build docker..."
      #   echo "Build OK"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test calc
        run: |
          echo "Testing calc..."
          echo "Test OK"
