name: cicd calc
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      # билдим образ и отправляем его в Docker Hub
      - name: Publishing a Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calc_flask:latest

  deploy:
    name: remote to host
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_NAME }}
          key: ${{ secrets.WINDOWS_KEY }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: pwd

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: test calc
        run: |
          echo "Testing calc..."
          echo "Test OK"
