name: cicd calc
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      # билдим образ и отправляем его в Docker Hub
      - name: Publishing a Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calc_flask:latest
  pull:
    needs: build
    runs-on: ubuntu-latest
    container: "${{ secrets.DOCKER_USERNAME }}/calc_flask:latest"
    steps:
      - name: pulling image on docker hub
        run: echo "pulling..."
    

  test:
    needs: pull
    runs-on: ubuntu-latest
    steps:
      - name: test calc
        run: |
          echo "Testing calc..."
          echo "Test OK"
