name: cicd calc
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      # билдим образ и отправляем его в Docker Hub
      - name: Publishing a Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calc_flask:latest

  deploy:
    name: remote to host
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script:
            "docker run -d -p 5000:5000 --name ${{ DOCKER_CONTAINER_NAME }} artemambrush/calc_flask"

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: test calc
        run:
          curl -o output.txt "http://31.184.253.55:5000/calc?arg1=10&arg2=7&operation=mult"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: output.txt
          name: out_curl
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: out_curl
      - name: login in host and stoping docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script:
            "docker stop ${{ DOCKER_CONTAINER_NAME }}"
